version: "3.8"

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_nginx
    expose:
      - 80/tcp
    ports:
      - 80:80
    restart: always
    volumes:
      - ./:/var/www/app
    depends_on:
      - php
      - mysql
    networks:
      - fenix_cinema_network

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_php
    restart: always
    volumes:
      - ./:/var/www/app
    networks:
      - fenix_cinema_network

  npm:
    build:
      context: ./docker
      dockerfile: npm.dockerfile
    container_name: ${APP_NAME}_npm
    volumes:
      - ./:/var/www/app
    networks:
      - fenix_cinema_network

  mysql:
    image: mysql
    container_name: ${APP_NAME}_mysql
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - phpmyadmin
    networks:
      - fenix_cinema_network

  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    expose:
      - 80/tcp
    ports:
      - 8000:80
    restart: always
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    networks:
      - fenix_cinema_network


networks:
  fenix_cinema_network:
    name: fenix_cinema_network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
